### ISSUE TITLE
启动时发生报错

### ISSUE THREAD

**Issue by simpleYOTO** [nek0us/nonebot-plugin-twitter#10]
![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/107185219/bb41d925-fbad-40c5-b6e1-9c76f699686e)
08-11 20:27:51 [ERROR] nonebot | Failed to import "nonebot_plugin_twitter"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\zhunxunbot\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.load_plugins("addtional_plugin/nonebot-plugin-twitter")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7qRsZznG-py3.9\lib\site-packages\nonebot\plugin\load.py", line 50, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7qRsZznG-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7qRsZznG-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7qRsZznG-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 146, in load_plugin
    module = importlib.import_module(
  File "C:\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7qRsZznG-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\zhunxunbot\zhenxun_bot\addtional_plugin\nonebot-plugin-twitter\nonebot_plugin_twitter\__init__.py", line 17, in <module>
    from nonebot_plugin_sendmsg_by_bots import tools
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7qRsZznG-py3.9\lib\site-packages\nonebot_plugin_sendmsg_by_bots\tools.py", line 42, in <module>
    async def send_group_msg_by_bots(group_id:int,msg:Message|MessageSegment|str) -> bool:
TypeError: unsupported operand type(s) for |: 'ABCMeta' and 'ABCMeta'

恳请大佬指教，已填写
twitter_proxy
twitter_qq
command_priority

**Comment by nek0us** [comment]
应该是python版本低了，更了个兼容性的包，
```bash
pip install nonebot-plugin-sendmsg-by-bots -U
```

**Comment by simpleYOTO** [comment]
我的python版本是3.9，更了您说的包后还是一样的结果：

**Comment by simpleYOTO** [comment]
![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/107185219/afdbde3b-4c91-4d1a-be68-d5b6747dbc32)

**Comment by simpleYOTO** [comment]
感谢感谢，已经可以了，感谢大佬
