### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by Parirose** [nek0us/nonebot-plugin-twitter#13]
11-06 20:10:50 [ERROR] nonebot | Failed to import "nonebot_plugin_twitter"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\nonebot\plugin\load.py", line 130,
 in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\nonebot\plugin\load.py", line 64,
in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\nonebot\plugin\manager.py", line 1
76, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\nonebot\plugin\manager.py", line 1
77, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\nonebot\plugin\manager.py", line 1
42, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_m
odule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\nonebot\plugin\manager.py", line 2
42, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\nonebot_plugin_twitter\__init__.py
", line 51, in <module>
    with Client(proxies=config_dev.twitter_proxy,http2=True) as client:
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\httpx\_client.py", line 682, in __
init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[BaseTransport]] = {
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\httpx\_client.py", line 685, in <d
ictcomp>
    else self._init_proxy_transport(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\httpx\_client.py", line 739, in _i
nit_proxy_transport
    return HTTPTransport(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\Ava\.venv\lib\site-packages\httpx\_transports\default.py", lin
e 149, in __init__
    self._pool = httpcore.HTTPProxy(
TypeError: HTTPProxy.__init__() got an unexpected keyword argument 'proxy_ssl_context'

**Comment by nek0us** [comment]
贴一下配置文件里的twitter_proxy配置

**Comment by Parirose** [comment]
> 贴一下配置文件里的twitter_proxy配置

twitter_website="https://nitter.privacydev.net"
twitter_proxy="http://127.0.0.1:7890"
twitter_qq=2854196306
command_priority=10

**Comment by nek0us** [comment]
https://nitter.privacydev.net 有些问题，所以我将它的优先级调到了最后，注释twitter_website试试呢？
如果还不行的话，看看
```bash
curl https://nitter.d420.de/elonmusk --proxy 127.0.0.1:7890
```
有无正常HTML返回

**Comment by Parirose** [comment]
> https://nitter.privacydev.net 有些问题，所以我将它的优先级调到了最后，注释twitter_website试试呢？ 如果还不行的话，看看
> 
> ```shell
> curl https://nitter.d420.de/elonmusk --proxy 127.0.0.1:7890
> ```
> 
> 有无正常HTML返回

是在控制台运行吗 抱歉我不是很懂
Invoke-WebRequest : 找不到接受实际参数“--proxy”的位置形式参数。
所在位置 行:1 字符: 1
+ curl https://nitter.d420.de/elonmusk --proxy 127.0.0.1:7890
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest]，ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by nek0us** [comment]
> > https://nitter.privacydev.net 有些问题，所以我将它的优先级调到了最后，注释twitter_website试试呢？ 如果还不行的话，看看
> > ```shell
> > curl https://nitter.d420.de/elonmusk --proxy 127.0.0.1:7890
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 有无正常HTML返回
> 
> 是在控制台运行吗 抱歉我不是很懂 Invoke-WebRequest : 找不到接受实际参数“--proxy”的位置形式参数。 所在位置 行:1 字符: 1
> 
>     * curl https://nitter.d420.de/elonmusk --proxy 127.0.0.1:7890
> 
>     * ```
>         + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest]，ParameterBindingException
>         + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
>       ```

你这个是powershell下的，可以打开个cmd用curl命令

**Comment by Parirose** [comment]
> > > https://nitter.privacydev.net 有些问题，所以我将它的优先级调到了最后，注释twitter_website试试呢？ 如果还不行的话，看看
> > > ```shell
> > > curl https://nitter.d420.de/elonmusk --proxy 127.0.0.1:7890
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 有无正常HTML返回
> > 
> > 
> > 是在控制台运行吗 抱歉我不是很懂 Invoke-WebRequest : 找不到接受实际参数“--proxy”的位置形式参数。 所在位置 行:1 字符: 1
> > ```
> > * curl https://nitter.d420.de/elonmusk --proxy 127.0.0.1:7890
> > 
> > * ```
> >     + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest]，ParameterBindingException
> >     + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
> >   ```
> > ```
> 
> 你这个是powershell下的，可以打开个cmd用curl命令

'curl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by nek0us** [comment]
你加一下我q吧，nekous后面跟企鹅邮箱

**Comment by Parirose** [comment]
> 你加一下我q吧，nekous后面跟企鹅邮箱

啊？抱歉没听明白

**Comment by nek0us** [comment]
> > 你加一下我q吧，nekous后面跟企鹅邮箱
> 
> 啊？抱歉没听明白 没找到q在哪

就是在qq上解决吧，我的qq号:nekous@qq.com

**Comment by Parirose** [comment]
> > > 你加一下我q吧，nekous后面跟企鹅邮箱
> > 
> > 
> > 啊？抱歉没听明白 没找到q在哪
> 
> 就是在qq上解决吧，我的qq号:[nekous@qq.com](mailto:nekous@qq.com)

啊？这咋加 抱歉我比较笨

**Comment by nek0us** [comment]
> > > > 你加一下我q吧，nekous后面跟企鹅邮箱
> > > 
> > > 
> > > 啊？抱歉没听明白 没找到q在哪
> > 
> > 就是在qq上解决吧，我的qq号:[nekous@qq.com](mailto:nekous@qq.com)
> 
> 啊？这咋加 抱歉我比较笨

邮箱也可以是qq号，可以直接搜

**Comment by Parirose** [comment]
> > > > > 你加一下我q吧，nekous后面跟企鹅邮箱
> > > > 
> > > > 
> > > > 啊？抱歉没听明白 没找到q在哪
> > > 
> > > 
> > > 就是在qq上解决吧，我的qq号:[nekous@qq.com](mailto:nekous@qq.com)
> > 
> > 
> > 啊？这咋加 抱歉我比较笨
> 
> 邮箱也可以是qq号，可以直接搜

要不哥你加下我 我这搜出来好多个结果
q：574485078
