### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by Xian0Grem** [nek0us/nonebot-plugin-twitter#24]
10-24 16:31:52 [ERROR] nonebot | Failed to import "nonebot_plugin_twitter"
Traceback (most recent call last):
  File "F:\NoneBot\nonebot_liyu\on_yinyou\bot.py", line 39, in <module>
    nonebot.load_plugin(pl)
  File "F:\NoneBot\nonebot_liyu\on_yinyou\.venv\Lib\site-packages\nonebot\plugin\load.py", line 40, in load_plugin
    return manager.load_plugin(module_path)
> File "F:\NoneBot\nonebot_liyu\on_yinyou\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Users\Xian_Grem\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "F:\NoneBot\nonebot_liyu\on_yinyou\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\NoneBot\nonebot_liyu\on_yinyou\.venv\Lib\site-packages\nonebot_plugin_twitter\__init__.py", line 19, in <module>
    from .config import Config,__version__,website_list,config_dev
  File "F:\NoneBot\nonebot_liyu\on_yinyou\.venv\Lib\site-packages\nonebot_plugin_twitter\config.py", line 18, in <module>
    class Config(BaseModel):
  File "F:\NoneBot\nonebot_liyu\on_yinyou\.venv\Lib\site-packages\nonebot_plugin_twitter\config.py", line 89, in Config
    @root_validator(pre=False)
  File "F:\NoneBot\nonebot_liyu\on_yinyou\.venv\Lib\site-packages\pydantic\deprecated\class_validators.py", line 240, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.9/u/root-validator-pre-skip

**Comment by nek0us** [comment]
还没修，暂不可用，等修了我通知你
