### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by Parirose** [nek0us/nonebot-plugin-twitter#3]
06-12 12:07:11 [ERROR] nonebot | Failed to import "nonebot_plugin_twitter"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\bot.py", line 14, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\load.py", line 125,
 in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\load.py", line 62,
in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 1
75, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 1
76, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 1
41, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_m
odule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 2
40, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot_plugin_twitter\__init__.py
", line 22, in <module>
    __plugin_meta__ = PluginMetadata(
TypeError: PluginMetadata.__init__() got an unexpected keyword argument 'type'

报错日志如上 不是很懂怎么解决 求大佬解惑

**Comment by nek0us** [comment]
更新nonebot2 2.0.0版本 
```
pip install nonebot2==2.0.0
```
不想升级的话，就去该插件目录下的 __init__.py 文件里删掉整个 plugin_meta 变量

**Comment by Parirose** [comment]
> 更新nonebot2 2.0.0版本
> 
> ```
> pip install nonebot2==2.0.0
> ```
> 
> 不想升级的话，就去该插件目录下的 **init**.py 文件里删掉整个 plugin_meta 变量

已经是nonebot2 2.0.0
删除变量后出现关注报错的问题
06-12 12:51:25 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_twitter) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\bot.py", line 17, in <module>
    nonebot.run()
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\__init__.py", line 309, in
 run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line
198, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\uvicorn\server.py", line 61, in ru
n
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_unt
il_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_
forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_for
ever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_o
nce
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\message.py", line 141, in
_check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\message.py", line 187, in
_run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\internal\matcher\matcher.p
y", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\internal\matcher\matcher.p
y", line 728, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot\dependencies\__init__.py",
 line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot_plugin_twitter\__init__.py
", line 175, in save_handle
    user_info = await get_user_info(data[0])
  File "C:\Users\Administrator\Desktop\ChatGPT3.5\nonebot\No1\.venv\lib\site-packages\nonebot_plugin_twitter\api.py", li
ne 23, in get_user_info
    result["screen_name"] = soup.find_all('a', class_='profile-card-fullname')[0].next
IndexError: list index out of range
以上是日志

**Comment by nek0us** [comment]
> 

更一下 插件0.1.6 版本试试看，记得重新删除元数据变量

**Comment by Parirose** [comment]
> 更新nonebot2 2.0.0版本
> 
> ```
> pip install nonebot2==2.0.0
> ```
> 
> 不想升级的话，就去该插件目录下的 **init**.py 文件里删掉整个 plugin_meta 变量



> > 
> 
> 更一下 插件0.1.6 版本试试看，记得重新删除元数据变量

已解决 感谢
